dashboard:
  states: []
  actions: []
  basicPlus: []
detailView:
  - label: "Jog"
    displayType: pushButton
    pushButton:
      command: push
    state: null
automation:
  conditions: []
  actions: []
id: winterplate04871.jog
version: 1
